# include:
#   - board: seeeduino_xiao_rp2040
#     shield: dasbob_left
#   - board: seeeduino_xiao_rp2040
#     shield: dasbob_right
inlcude:
    - board: seeeduino_xiao_rp2040
      shield: dasbob_test
